# Generated by Django 4.2.30 on 2026-07-21 18:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='email',
            field=models.EmailField(blank=True, max_length=254),
        ),
        migrations.AddField(
            model_name='client',
            name='phone_number',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='jobcard',
            name='device_sn',
            field=models.CharField(blank=True, max_length=100, verbose_name='Device S/N'),
        ),
        migrations.AddField(
            model_name='jobcard',
            name='risk_confined_space',
            field=models.BooleanField(default=False, verbose_name='Working in Confined space'),
        ),
        migrations.AddField(
            model_name='jobcard',
            name='risk_dust_noise',
            field=models.BooleanField(default=False, verbose_name='Dust from drilling & noise'),
        ),
        migrations.AddField(
            model_name='jobcard',
            name='risk_height',
            field=models.BooleanField(default=False, verbose_name='Working at height'),
        ),
        migrations.AddField(
            model_name='jobcard',
            name='safety_harness',
            field=models.BooleanField(default=False, verbose_name='Safety harness'),
        ),
        migrations.AddField(
            model_name='jobcard',
            name='safety_ladder',
            field=models.BooleanField(default=False, verbose_name='Using a step ladder'),
        ),
        migrations.AddField(
            model_name='jobcard',
            name='safety_mask',
            field=models.BooleanField(default=False, verbose_name='Using ear plugs and dust mask'),
        ),
        migrations.AddField(
            model_name='jobcard',
            name='safety_ppe',
            field=models.BooleanField(default=False, verbose_name='Wearing full PPE'),
        ),
        migrations.AddField(
            model_name='jobcard',
            name='work_start_date',
            field=models.DateField(blank=True, null=True, verbose_name='Work Start Date'),
        ),
        migrations.CreateModel(
            name='TimeLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_time', models.DateTimeField()),
                ('end_time', models.DateTimeField()),
                ('hours_worked', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('engineer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='time_logs', to='jobs.engineer')),
                ('job_card', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='time_logs', to='jobs.jobcard')),
            ],
            options={
                'ordering': ['start_time'],
            },
        ),
    ]
